export const NAME_MAP = {
  weekFrom: "dia1",
  weekTo: "dia2",
  month: "mes",
  shortYear: "año",
  school: "centro_docente",
  professor: "profesor",
  company: "centro_trabajo",
  mentor: "tutor",
  alumn: "alumno",
  grade: "ciclo",
  gradeType: "grado",
  activity1: "actividad0",
  activity2: "actividad1",
  activity3: "actividad2",
  activity4: "actividad3",
  activity5: "actividad4",
  observations1: "observaciones0",
  observations2: "observaciones1",
  observations3: "observaciones2",
  observations4: "observaciones3",
  observations5: "observaciones4",
  time1: "tiempo0",
  time2: "tiempo1",
  time3: "tiempo2",
  time4: "tiempo3",
  time5: "tiempo4",
  professorSign: "firma_profe",
  alumnSign: "firma_alumno",
  mentorSign: "firma_tutor",
  sheetNumber: "hoja1",
  maxSheets: "hoja2"
};
export const MONTHS = [
  "Enero",
  "Febrero",
  "Marzo",
  "Abril",
  "Mayo",
  "Junio",
  "Julio",
  "Agosto",
  "Septiembre",
  "Octubre",
  "Noviembre",
  "Diciembre"
];
